#ifndef PASSIVEINCOME_H
#define PASSIVEINCOME_H

#include "Money.h"
#include "House.h"
#include "Happiness.h"
#include <iostream>
#include <vector>

class PassiveIncome {
private:
    Money& money;
    int totalIncome; // Tracks the total passive income generated
	int income; // Tracks the income generated by a single house
	Happiness& happiness;
	std::vector<House::HouseType>& builtHouses;
public:
    PassiveIncome(Money& money, std::vector<House::HouseType>& builtHouses, Happiness& happiness);

    void generateIncome(House::HouseType houseType);
    int getTotalIncome() const;
    void addIncome(House::HouseType houseType);
    void removeIncome(House::HouseType houseType);
};

#endif // PASSIVE_INCOME_H